layout_spectrum: 0.3215583
typography_spectrum: 0.5082642
color:
  saturation: 0.04709812
  lightness: 0.787687
  brandStrength: 0.2963172
  rhythmicContrast: 0.92765
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: PicTale Photo
