color:
  saturation: 0.04709812
  brandStrength: 0.2963172
  rhythmicContrast: 0.92765
  lightness: 0.787687
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.2798066
typography_spectrum: 0.3657357
name: PicTale Photo
